export {
  hasPermission,
  isAdmin,
  canManageUsers,
  canManageRequests,
  canManageContent,
  canManageGroups,
  canManageOwnGroupOnly,
  canManageEvents,
  canManageBookings,
  canAccessDirectory,
  canManageSettings,
  canAccessHouseholds,
  getPermissions,
  canPublishAnnouncements,
  requireRole,
  ROLE_PERMISSIONS,
  type Permission,
} from '@shared/lib';
export type { Role } from '@shared/lib';
