import { pgEnum } from 'drizzle-orm/pg-core';

export const disputeEventTypeEnum = pgEnum('DisputeEventType', ['CREATED', 'SUBMITTED', 'ASSIGNED', 'MEDIATION_OFFERED', 'MEDIATION_ACCEPTED', 'MEDIATION_DECLINED', 'MEDIATION_CONCLUDED', 'RULING_ISSUED', 'RESOLVED', 'WITHDRAWN', 'ESCALATED_CSOS', 'CSOS_CLOSED', 'NOTE_ADDED', 'EVIDENCE_ADDED', 'STATUS_CHANGED']);