apis:
  netcomplex@v1:
    root: ./public/openapi.json
    x-openapi-version: '3.1.0'

rules:
  no-server-trailing-slash: error
  no-empty-servers: warn
  operation-4xx-response: warn
  operation-operationId: warn
  path-parameters-defined: error
