-- =============================================================================
-- Composite indexes for RLS predicate plans (BD soralia-village-4a6, step 7)
--
-- The RLS policies in 20260604000000_add_rls_policies filter on
-- ("tenantId", "userId") for the user-scoped tables. The existing
-- @@index([userId]) indexes do not cover "tenantId" — Postgres can use them,
-- but the planner must read more rows than necessary to evaluate the
-- tenant predicate. A composite ("tenantId", "userId") index matches the
-- RLS predicate exactly.
--
-- Scope: only the two user-scoped tables in the RLS migration scope.
--   - Notification: residents see only their own; admins see all in tenant.
--   - MaintenanceRequest: future user-scoping (e.g. resident-visible
--     maintenance history) will benefit. Currently tenant-only in scope,
--     but the index is cheap insurance.
--
-- Out of scope (deferred with the rest of the deferred tables): Booking,
-- Message, Conversation, ConversationParticipant, RequestNote,
-- RequestHistory. Those will get composite indexes in BD soralia-village-t78.
-- =============================================================================

-- CreateIndex
CREATE INDEX "Notification_tenantId_userId_idx" ON "Notification"("tenantId", "userId");
