export const DWalletStreams = [
  {
    key: 'survey_participation',
    label: 'Survey Participation',
    description: 'Controls data usage for third-party surveys',
    residentSharePct: 20,
    isActive: true,
  },
  {
    key: 'marketplace_activity',
    label: 'Marketplace Activity',
    description: 'Controls data usage for marketplace analytics',
    residentSharePct: 20,
    isActive: true,
  },
  {
    key: 'agent_transactions',
    label: 'Agent Transactions',
    description: 'Controls data usage for agent marketplace',
    residentSharePct: 20,
    isActive: true,
  },
  {
    key: 'value_added_services',
    label: 'Value-Added Services',
    description: 'Controls data usage for VAS improvement',
    residentSharePct: 20,
    isActive: true,
  },
  {
    key: 'service_provider_listings',
    label: 'Service Provider Listings',
    description: 'Controls data usage for provider analytics',
    residentSharePct: 10,
    isActive: true,
  },
  {
    key: 'premium_placements',
    label: 'Premium Placements',
    description: 'Controls data usage for listing analytics',
    residentSharePct: 10,
    isActive: true,
  },
  {
    key: 'agent_registrations',
    label: 'Agent Registrations',
    description: 'Controls data usage for agent registration data',
    residentSharePct: 10,
    isActive: true,
  },
  {
    key: 'agent_premium_listings',
    label: 'Agent Premium Listings',
    description: 'Controls data usage for premium listing data',
    residentSharePct: 10,
    isActive: true,
  },
];
