export { StatsWidget, StatCard } from './StatsWidget';
export { QuickActionsWidget } from './QuickActionsWidget';
export { RecentActivityWidget } from './RecentActivityWidget';
export { EventsWidget } from './EventsWidget';
export { NotificationsWidget } from './NotificationsWidget';
export { MessagesWidget } from './MessagesWidget';
export { DraggableWidget } from './DraggableWidget';
export { DashboardTabs, AddWidgetModal } from './DashboardTabs';
export { HouseholdsWidget } from './HouseholdsWidget';
export { AgentDashboardWidget } from './AgentDashboardWidget';
export { SoloSeatWidget } from './SoloSeatWidget';
export { WidgetRenderer } from './WidgetRenderer';
export { UserContentWidget } from './UserContentWidget';
export { DashboardStats } from './DashboardStats';
export type { DashboardTab } from './DashboardTabs';
