import { readFileSync, writeFileSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { resolve, relative } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname;
const SRC = resolve(ROOT, 'src');
const CATALOG_PATH = resolve(ROOT, 'docs/reports/EVENT_CATALOG.md');

/* ── Parse declared event types from emitter.ts ─────── */
const emitterPath = resolve(SRC, 'shared/api/events/emitter.ts');
const source = readFileSync(emitterPath, 'utf-8');

const eventTypes: string[] = [];
for (const line of source.split('\n')) {
  const m = line.match(/\| \{ type: '([^']+)'/);
  if (m) eventTypes.push(m[1]);
}

/* ── Parse EVENT_TYPES array from listener.ts (variable-based consumers) ── */
const listenerPath = resolve(SRC, 'shared/api/achievements/listener.ts');
const listenerSource = readFileSync(listenerPath, 'utf-8');

const variableConsumers = new Set<string>();
let inArray = false;
for (const line of listenerSource.split('\n')) {
  if (line.includes('EVENT_TYPES:')) inArray = true;
  else if (inArray) {
    const m = line.match(/'([^']+)'/);
    if (m) variableConsumers.add(m[1]);
    if (line.includes('];')) inArray = false;
  }
}

interface EventInfo {
  producers: Set<string>;
  consumers: Set<string>;
}

const info: Record<string, EventInfo> = {};
for (const t of eventTypes) {
  info[t] = { producers: new Set(), consumers: new Set() };
}

/* ── Single ripgrep pass: capture all emitEvent/registerHandler/onEvent calls ── */
const combinedPattern = `^.*\\b(emitEvent|registerHandler|onEvent)\\s*\\(\\s*'([^']+)'`;
try {
  const raw = execSync(
    `rg -n -H "${combinedPattern}" --glob '!**/emitter.ts' ${SRC} 2>/dev/null || true`,
    { encoding: 'utf-8', maxBuffer: 16 * 1024 * 1024 }
  );

  for (const line of raw.split('\n')) {
    if (!line) continue;
    /* Format: file.ts:lineNo:code */
    const match = line.match(/^([^:]+):(\d+):(.*)$/);
    if (!match) continue;
    const [, file, , code] = match;
    const m = code.match(/\b(emitEvent|registerHandler|onEvent)\s*\(\s*'([^']+)'/);
    if (!m) continue;
    const [, fn, type] = m;
    if (!info[type]) continue;
    const rel = file.replace(SRC + '/', 'src/');
    if (fn === 'emitEvent') info[type].producers.add(rel);
    else info[type].consumers.add(rel);
  }
} catch {
  /* rg not found or empty — proceed with empty sets */
}

/* Variable-based consumer (EVENT_TYPES array) */
for (const type of variableConsumers) {
  if (info[type]) info[type].consumers.add(`src/shared/api/achievements/listener.ts`);
}

const FUTURE_EVENTS = new Set([
  'merit.recognized', // declared, never emitted — reserve for Community Merits
]);

let exitCode = 0;

console.log('\n── Domain Event Contract ──\n');

for (const type of eventTypes) {
  const producers = Array.from(info[type].producers);
  const consumers = Array.from(info[type].consumers);
  const isFuture = FUTURE_EVENTS.has(type);
  const pc = producers.length;
  const cc = consumers.length;
  const hasProducer = pc > 0;
  const hasConsumer = cc > 0;
  const status = hasProducer && hasConsumer ? 'OK' : isFuture && !hasProducer ? 'FUTURE' : isFuture ? 'WAIVED' : 'ISSUE';
  const marker = status === 'OK' ? '✓' : status === 'FUTURE' ? '◷' : status === 'WAIVED' ? '◦' : '⚠';

  console.log(` ${marker} ${type}  producers=${pc}  consumers=${cc}  ${status}`);

  if (!hasProducer && !isFuture) {
    console.log(`     No emitEvent('${type}') call site found`);
    exitCode = 1;
  }
  if (!hasConsumer) {
    console.log(`     No handler registered for '${type}'`);
    if (!isFuture) exitCode = 1;
  }
  if (hasProducer && hasConsumer) {
    for (const f of producers) console.log(`     emit → ${f}`);
    for (const f of consumers) console.log(`     on   → ${f}`);
  }
}

/* ── Generate catalog ───────────────────────────────── */
const rows = eventTypes.map(type => {
  const producers = Array.from(info[type].producers);
  const consumers = Array.from(info[type].consumers);
  const isFuture = FUTURE_EVENTS.has(type);
  const pc = producers.length;
  const cc = consumers.length;
  const hasProducer = pc > 0;
  const hasConsumer = cc > 0;
  const status = hasProducer && hasConsumer ? 'active' : isFuture ? 'future' : 'unconsumed';
  return `| \`${type}\` | 1 | ${producers.join(', ') || '—'} | ${consumers.join(', ') || '—'} | ${status} | platform |`;
});

const catalog = `# Event Catalog

> Auto-generated by \`scripts/check-domain-events.ts\`. Do not edit manually.
> Generated: ${new Date().toISOString().slice(0, 10)}

| Event | Version | Producers | Consumers (Lane A) | Status | Owner |
|---|---|---|---|---|---|
${rows.join('\n')}
`;

writeFileSync(CATALOG_PATH, catalog, 'utf-8');
console.log(`\n📄 Catalog written to ${relative(ROOT, CATALOG_PATH)}`);
console.log(exitCode === 0 ? '✅ All events OK' : '❌ Contract violations found');
process.exit(exitCode);
