/**
 * build-provider-invoice-pdf.ts — Provider Invoice PDF Builder
 *
 * Pure function: data → Uint8Array PDF bytes.
 * Uses shared pdf-utils (Phase 109 extraction).
 */
import { PDFDocument, rgb } from 'pdf-lib';
import {
  A4_WIDTH,
  MARGIN,
  LINE_HEIGHT,
  createPdfContext,
  newPage,
  checkPageBreak,
  drawSectionHeader,
  drawLine,
} from './pdf-utils';

export interface ProviderInvoiceData {
  invoiceNumber: string;
  invoiceDate: string;
  providerName: string;
  providerId: string;
  tenantName: string;
  items: Array<{ description: string; amount: string }>;
  subtotal: string;
  platformFee: string;
  processorFee: string;
  netAmount: string;
  total: string;
  currency: string;
  status: string;
  paidAt: string | null;
}

export async function buildProviderInvoicePdf(data: ProviderInvoiceData): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const ctx = await createPdfContext(pdfDoc);

  pdfDoc.setTitle(`Provider Invoice — ${data.invoiceNumber}`);
  pdfDoc.setAuthor('NetComplex Provider Platform');
  pdfDoc.setCreationDate(new Date());

  // ── Header ──
  drawLine(ctx, 'PROVIDER INVOICE', { font: ctx.bold, indent: 0 });
  ctx.page.drawText(data.invoiceNumber, {
    x: A4_WIDTH - MARGIN - 150,
    y: ctx.y + LINE_HEIGHT,
    size: 11,
    font: ctx.font,
    color: rgb(0.4, 0.4, 0.4),
  });
  ctx.y -= LINE_HEIGHT * 2;

  drawLine(ctx, `Date: ${data.invoiceDate}`);
  drawLine(ctx, `Status: ${data.status}${data.paidAt ? ` (paid ${data.paidAt})` : ''}`);
  ctx.y -= LINE_HEIGHT;

  // ── Section 1: Parties ──
  drawSectionHeader(ctx, 'Parties');
  drawLine(ctx, `Provider: ${data.providerName} (${data.providerId})`);
  drawLine(ctx, `Tenant: ${data.tenantName}`);
  ctx.y -= LINE_HEIGHT;

  // ── Section 2: Line Items ──
  drawSectionHeader(ctx, 'Line Items');
  for (const item of data.items) {
    drawLine(ctx, item.description);
    const amountLabel = `${data.currency} ${item.amount}`;
    ctx.page.drawText(amountLabel, {
      x: A4_WIDTH - MARGIN - 150,
      y: ctx.y + LINE_HEIGHT,
      size: 11,
      font: ctx.font,
      color: rgb(0, 0, 0),
    });
    ctx.y -= LINE_HEIGHT;
  }
  ctx.y -= LINE_HEIGHT * 0.5;

  // ── Section 3: Totals ──
  drawSectionHeader(ctx, 'Summary');
  drawLine(ctx, `Platform Fee: ${data.currency} ${data.platformFee}`);
  drawLine(ctx, `Processor Fee: ${data.currency} ${data.processorFee}`);
  drawLine(ctx, `Net Payout: ${data.currency} ${data.netAmount}`, { font: ctx.bold });
  ctx.y -= LINE_HEIGHT * 0.5;
  drawLine(ctx, `Total: ${data.currency} ${data.total}`, { font: ctx.bold });
  ctx.y -= LINE_HEIGHT * 2;

  // ── Footer ──
  checkPageBreak(pdfDoc, ctx, LINE_HEIGHT * 3);
  if (ctx.y < 80) {
    newPage(pdfDoc, ctx);
  }
  ctx.page.drawText(
    'This invoice was automatically generated by the NetComplex Provider Platform.',
    {
      x: MARGIN,
      y: 60,
      size: 9,
      font: ctx.font,
      color: rgb(0.5, 0.5, 0.5),
    }
  );

  return await pdfDoc.save();
}
