import type {
  SubscriptionTierInput,
  ProviderReputationInput,
  ProviderMeritInput,
  ProviderSubscriptionInput,
  PaymentTransactionInput,
  ProviderChargeInput,
  ProviderInvoiceInput,
  RevenueRecordInput,
} from '../types';

export const subscriptionTiers: SubscriptionTierInput[] = [
  {
    id: 'tier-basic',
    name: 'Basic',
    description: 'Free tier for community providers getting started.',
    price: '0',
    currency: 'ZAR',
    maxListings: 3,
    features: { analytics: 'standard', promotion: false },
    platformFeePercent: '10',
    verificationRequired: false,
  },
  {
    id: 'tier-pro',
    name: 'Professional',
    description: 'Verified provider tier with advanced features.',
    price: '29900',
    currency: 'ZAR',
    maxListings: 50,
    features: { analytics: 'advanced', promotion: true },
    platformFeePercent: '8',
    verificationRequired: true,
  },
  {
    id: 'tier-enterprise',
    name: 'Enterprise',
    description: 'Top-tier for premium service providers.',
    price: '99900',
    currency: 'ZAR',
    maxListings: null,
    features: { analytics: 'premium', promotion: true },
    platformFeePercent: '5',
    verificationRequired: true,
  },
];

export const providerReputations: ProviderReputationInput[] = [
  {
    id: 'credit-pipe-burst',
    providerId: 'prov-pipe-burst',
    totalScore: 245,
    responseTimeScore: 72,
    qualityScore: 88,
    reviewScore: 65,
    complianceScore: 90,
    engagementScore: 80,
    lastCalculatedAt: new Date('2026-06-22'),
  },
  {
    id: 'credit-tree-felling',
    providerId: 'prov-tree-felling',
    totalScore: 180,
    responseTimeScore: 60,
    qualityScore: 75,
    reviewScore: 55,
    complianceScore: 85,
    engagementScore: 70,
    lastCalculatedAt: new Date('2026-06-21'),
  },
];

export const providerMerits: ProviderMeritInput[] = [
  {
    id: 'merit-pipe-1',
    providerId: 'prov-pipe-burst',
    meritType: 'RESPONSE_TIME',
    points: 30,
    description: 'Responded to emergency plumbing request within 15 minutes',
    referenceId: 'mr-burst-pipe',
  },
  {
    id: 'merit-pipe-2',
    providerId: 'prov-pipe-burst',
    meritType: 'SERVICE_QUALITY',
    points: 25,
    description: 'Completed job with positive resident feedback',
    referenceId: 'mr-burst-pipe',
  },
  {
    id: 'merit-pipe-3',
    providerId: 'prov-pipe-burst',
    meritType: 'COMPLIANCE',
    points: 20,
    description: 'Updated insurance certificates on time',
    referenceId: null,
  },
  {
    id: 'merit-pipe-4',
    providerId: 'prov-pipe-burst',
    meritType: 'ENGAGEMENT',
    points: 15,
    description: 'Attended quarterly provider workshop',
    referenceId: null,
  },
];

export const providerSubscriptions: ProviderSubscriptionInput[] = [
  {
    id: 'sub-pipe-pro',
    providerId: 'prov-pipe-burst',
    tierId: 'tier-pro',
    status: 'ACTIVE',
    startDate: new Date('2026-01-15'),
    endDate: null,
    nextBillingDate: new Date('2026-07-15'),
    price: '29900',
    currency: 'ZAR',
    paymentGateway: 'PAYSTACK',
  },
];

export const paymentTransactions: PaymentTransactionInput[] = [
  {
    id: 'tx-pipe-jan',
    providerId: 'prov-pipe-burst',
    subscriptionId: 'sub-pipe-pro',
    amount: '29900',
    currency: 'ZAR',
    platformFee: '2392',
    processorFee: '897',
    netAmount: '26611',
    status: 'COMPLETED',
    gateway: 'PAYSTACK',
    externalRef: 'pay_jan2026_001',
    invoiceUrl: null,
  },
  {
    id: 'tx-pipe-feb',
    providerId: 'prov-pipe-burst',
    subscriptionId: 'sub-pipe-pro',
    amount: '29900',
    currency: 'ZAR',
    platformFee: '2392',
    processorFee: '897',
    netAmount: '26611',
    status: 'COMPLETED',
    gateway: 'PAYSTACK',
    externalRef: 'pay_feb2026_002',
    invoiceUrl: null,
  },
  {
    id: 'tx-pipe-mar',
    providerId: 'prov-pipe-burst',
    subscriptionId: 'sub-pipe-pro',
    amount: '29900',
    currency: 'ZAR',
    platformFee: '2392',
    processorFee: '897',
    netAmount: '26611',
    status: 'COMPLETED',
    gateway: 'PAYSTACK',
    externalRef: 'pay_mar2026_003',
    invoiceUrl: null,
  },
];

export const providerCharges: ProviderChargeInput[] = [
  {
    id: 'chg-pipe-jan',
    providerId: 'prov-pipe-burst',
    subscriptionId: 'sub-pipe-pro',
    transactionId: 'tx-pipe-jan',
    description: 'Professional tier — January 2026',
    amount: '29900',
    currency: 'ZAR',
    status: 'PAID',
    gateway: 'PAYSTACK',
    externalRef: 'ch_jan2026_001',
    dueDate: new Date('2026-01-15'),
    paidAt: new Date('2026-01-15'),
  },
  {
    id: 'chg-pipe-feb',
    providerId: 'prov-pipe-burst',
    subscriptionId: 'sub-pipe-pro',
    transactionId: 'tx-pipe-feb',
    description: 'Professional tier — February 2026',
    amount: '29900',
    currency: 'ZAR',
    status: 'PAID',
    gateway: 'PAYSTACK',
    externalRef: 'ch_feb2026_002',
    dueDate: new Date('2026-02-15'),
    paidAt: new Date('2026-02-15'),
  },
  {
    id: 'chg-pipe-mar',
    providerId: 'prov-pipe-burst',
    subscriptionId: 'sub-pipe-pro',
    transactionId: 'tx-pipe-mar',
    description: 'Professional tier — March 2026',
    amount: '29900',
    currency: 'ZAR',
    status: 'PAID',
    gateway: 'PAYSTACK',
    externalRef: 'ch_mar2026_003',
    dueDate: new Date('2026-03-15'),
    paidAt: new Date('2026-03-15'),
  },
];

export const providerInvoices: ProviderInvoiceInput[] = [
  {
    id: 'inv-pipe-jan',
    providerId: 'prov-pipe-burst',
    subscriptionId: 'sub-pipe-pro',
    transactionId: 'tx-pipe-jan',
    invoiceNumber: 'INV-2026-0001',
    items: [
      { description: 'Professional tier subscription (Jan)', amount: '29900' },
      { description: 'Platform fee (8%)', amount: '-2392' },
      { description: 'Processor fee (3%)', amount: '-897' },
    ],
    total: '29900',
    platformFee: '2392',
    processorFee: '897',
    netAmount: '26611',
    currency: 'ZAR',
    status: 'PAID',
    paidAt: new Date('2026-01-15'),
    pdfUrl: null,
  },
  {
    id: 'inv-pipe-feb',
    providerId: 'prov-pipe-burst',
    subscriptionId: 'sub-pipe-pro',
    transactionId: 'tx-pipe-feb',
    invoiceNumber: 'INV-2026-0002',
    items: [
      { description: 'Professional tier subscription (Feb)', amount: '29900' },
      { description: 'Platform fee (8%)', amount: '-2392' },
      { description: 'Processor fee (3%)', amount: '-897' },
    ],
    total: '29900',
    platformFee: '2392',
    processorFee: '897',
    netAmount: '26611',
    currency: 'ZAR',
    status: 'PAID',
    paidAt: new Date('2026-02-15'),
    pdfUrl: null,
  },
];

export const revenueRecords: RevenueRecordInput[] = [
  {
    id: 'rev-pipe-jan',
    providerId: 'prov-pipe-burst',
    transactionId: 'tx-pipe-jan',
    grossAmount: '29900',
    platformFee: '2392',
    processorFee: '897',
    netAmount: '26611',
    currency: 'ZAR',
    period: '2026-01',
  },
  {
    id: 'rev-pipe-feb',
    providerId: 'prov-pipe-burst',
    transactionId: 'tx-pipe-feb',
    grossAmount: '29900',
    platformFee: '2392',
    processorFee: '897',
    netAmount: '26611',
    currency: 'ZAR',
    period: '2026-02',
  },
];
