import type { GroupInput, GroupMemberInput } from '../types';

export const groups: GroupInput[] = [
  {
    id: 'group-gardening',
    name: 'Gardening Group',
    description: 'Share tips, seeds, and plants with fellow gardening enthusiasts.',
    category: 'gardening',
    color: '#22c55e',
    isPublic: true,
    residentFilter: 'ALL',
    ownerId: 'user-john-smith',
  },
  {
    id: 'group-fitness',
    name: 'Fitness Group',
    description: 'Stay active with morning walks, yoga, and group workouts.',
    category: 'fitness',
    color: '#f59e0b',
    isPublic: true,
    residentFilter: 'ALL',
    ownerId: 'user-michael-chen',
  },
  {
    id: 'group-book-club',
    name: 'Book Club',
    description: 'Monthly book discussions and author visits.',
    category: 'book-club',
    color: '#8b5cf6',
    isPublic: true,
    residentFilter: 'ALL',
    ownerId: 'user-emma-williams',
  },
  {
    id: 'group-cooking',
    name: 'Cooking Club',
    description: 'Share recipes, potlucks, and cooking demonstrations.',
    category: 'cooking',
    color: '#ef4444',
    isPublic: true,
    residentFilter: 'ALL',
    ownerId: 'user-emma-williams',
  },
  {
    id: 'group-photography',
    name: 'Photography Club',
    description: 'Capture beautiful moments in Soralia Village.',
    category: 'photography',
    color: '#06b6d4',
    isPublic: true,
    residentFilter: 'ALL',
    ownerId: 'user-michael-chen',
  },
  {
    id: 'group-volunteering',
    name: 'Volunteering Group',
    description: 'Make a difference in our community through service.',
    category: 'volunteering',
    color: '#ec4899',
    isPublic: true,
    residentFilter: 'ALL',
    ownerId: 'user-sarah-mitchell',
  },
];

export const groupMembers: GroupMemberInput[] = [
  {
    id: 'ug-john-gardening',
    userId: 'user-john-smith',
    groupId: 'group-gardening',
    role: 'ADMIN',
  },
  {
    id: 'ug-sarah-gardening',
    userId: 'user-sarah-mitchell',
    groupId: 'group-gardening',
    role: 'ADMIN',
  },
  {
    id: 'ug-michael-fitness',
    userId: 'user-michael-chen',
    groupId: 'group-fitness',
    role: 'ADMIN',
  },
  {
    id: 'ug-emma-bookclub',
    userId: 'user-emma-williams',
    groupId: 'group-book-club',
    role: 'ADMIN',
  },
  {
    id: 'ug-john-bookclub',
    userId: 'user-john-smith',
    groupId: 'group-book-club',
    role: 'MEMBER',
  },
  {
    id: 'ug-anna-bookclub',
    userId: 'user-anna-patel',
    groupId: 'group-book-club',
    role: 'MEMBER',
  },
  {
    id: 'ug-michael-photography',
    userId: 'user-michael-chen',
    groupId: 'group-photography',
    role: 'ADMIN',
  },
  {
    id: 'ug-lisa-photography',
    userId: 'user-lisa-chen',
    groupId: 'group-photography',
    role: 'MEMBER',
  },
  {
    id: 'ug-emma-cooking',
    userId: 'user-emma-williams',
    groupId: 'group-cooking',
    role: 'ADMIN',
  },
  { id: 'ug-anna-cooking', userId: 'user-anna-patel', groupId: 'group-cooking', role: 'MEMBER' },
  {
    id: 'ug-priya-cooking',
    userId: 'user-priya-naidoo',
    groupId: 'group-cooking',
    role: 'MEMBER',
  },
  {
    id: 'ug-david-volunteering',
    userId: 'user-david-vdm',
    groupId: 'group-volunteering',
    role: 'ADMIN',
  },
  {
    id: 'ug-marcus-volunteering',
    userId: 'user-marcus-johnson',
    groupId: 'group-volunteering',
    role: 'MEMBER',
  },
  {
    id: 'ug-fatima-gardening',
    userId: 'user-fatima-hassan',
    groupId: 'group-gardening',
    role: 'MEMBER',
  },
];
