import type {
  PropertyInput,
  HouseholdInput,
  ProfileInput,
  StandardSeatInput,
  SoloSeatInput,
  PremiumSeatInput,
} from '../types';

export const properties: PropertyInput[] = [
  {
    id: 'prop-001',
    platformAddress: 'unit012@soralia.org',
    street: 'Pagoda Rd',
    unit: '12',
    ownerId: 'user-john-smith',
    homeImage: '/assets/images/home1.jpg',
  },
  {
    id: 'prop-002',
    platformAddress: 'unit008@soralia.org',
    street: 'Wild Almond Rd',
    unit: '8',
    ownerId: 'user-sarah-mitchell',
    homeImage: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80',
  },
  {
    id: 'prop-003',
    platformAddress: 'unit003@soralia.org',
    street: 'Silkypuff St',
    unit: '3',
    ownerId: 'user-michael-chen',
    homeImage: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80',
  },
  {
    id: 'prop-004',
    platformAddress: 'unit005@soralia.org',
    street: 'Conebrush Rd',
    unit: '5',
    ownerId: 'user-robert-wilson',
    homeImage: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80',
  },
  {
    id: 'prop-005',
    platformAddress: 'unit017@soralia.org',
    street: 'Beechwood',
    unit: '17',
    ownerId: 'user-anna-patel',
    homeImage: 'https://images.unsplash.com/photo-1572120360610-d971b9d7767c?w=800&q=80',
  },
  {
    id: 'prop-006',
    platformAddress: 'unit022@soralia.org',
    street: 'Sugarbrush',
    unit: '22',
    ownerId: 'user-marcus-johnson',
    homeImage: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
  },
];

export const households: HouseholdInput[] = [
  {
    id: 'hh-001',
    propertyId: 'prop-001',
    occupancyType: 'OWNER_OCCUPIED',
    moveInDate: new Date('2023-01-15'),
  },
  {
    id: 'hh-002',
    propertyId: 'prop-002',
    occupancyType: 'OWNER_OCCUPIED',
    moveInDate: new Date('2022-08-20'),
  },
  {
    id: 'hh-003',
    propertyId: 'prop-003',
    occupancyType: 'OWNER_OCCUPIED',
    moveInDate: new Date('2024-03-10'),
  },
  {
    id: 'hh-004',
    propertyId: 'prop-004',
    occupancyType: 'RENTAL',
    moveInDate: new Date('2025-06-01'),
  },
  {
    id: 'hh-005',
    propertyId: 'prop-005',
    occupancyType: 'OWNER_OCCUPIED',
    moveInDate: new Date('2023-09-01'),
  },
  {
    id: 'hh-006',
    propertyId: 'prop-006',
    occupancyType: 'OWNER_OCCUPIED',
    moveInDate: new Date('2024-01-20'),
  },
];

export const profiles: ProfileInput[] = [
  {
    id: 'prof-john',
    householdId: 'hh-001',
    userId: 'user-john-smith',
    displayName: 'John Smith',
    profileAddress: 'unit012@soralia.org',
    householdRole: 'OCCUPANT',
    residencyType: 'OWNER',
    occupantSince: new Date('2023-01-15'),
  },
  {
    id: 'prof-emma',
    householdId: 'hh-001',
    userId: 'user-emma-williams',
    displayName: 'Emma Williams',
    profileAddress: 'unit012@soralia.org',
    householdRole: 'FAMILY',
    residencyType: 'FAMILY',
    occupantSince: new Date('2023-01-15'),
  },
  {
    id: 'prof-sarah',
    householdId: 'hh-002',
    userId: 'user-sarah-mitchell',
    displayName: 'Sarah Mitchell',
    profileAddress: 'unit008@soralia.org',
    householdRole: 'OCCUPANT',
    residencyType: 'OWNER',
    occupantSince: new Date('2022-08-20'),
  },
  {
    id: 'prof-michael',
    householdId: 'hh-003',
    userId: 'user-michael-chen',
    displayName: 'Michael Chen',
    profileAddress: 'unit003@soralia.org',
    householdRole: 'OCCUPANT',
    residencyType: 'OWNER',
    occupantSince: new Date('2024-03-10'),
  },
  {
    id: 'prof-lisa',
    householdId: 'hh-003',
    userId: 'user-lisa-chen',
    displayName: 'Lisa Chen',
    profileAddress: 'unit003@soralia.org',
    householdRole: 'FAMILY',
    residencyType: 'FAMILY',
    occupantSince: new Date('2024-03-10'),
  },
  {
    id: 'prof-anna',
    householdId: 'hh-004',
    userId: 'user-anna-patel',
    displayName: 'Anna Patel',
    profileAddress: 'unit005@soralia.org',
    householdRole: 'OCCUPANT',
    residencyType: 'RENTER',
    occupantSince: new Date('2025-06-01'),
  },
  {
    id: 'prof-priya',
    householdId: 'hh-005',
    userId: 'user-priya-naidoo',
    displayName: 'Priya Naidoo',
    profileAddress: 'unit017@soralia.org',
    householdRole: 'OCCUPANT',
    residencyType: 'OWNER',
    occupantSince: new Date('2023-09-01'),
  },
  {
    id: 'prof-marcus',
    householdId: 'hh-006',
    userId: 'user-marcus-johnson',
    displayName: 'Marcus Johnson',
    profileAddress: 'unit022@soralia.org',
    householdRole: 'OCCUPANT',
    residencyType: 'OWNER',
    occupantSince: new Date('2024-01-20'),
  },
  {
    id: 'prof-james',
    householdId: 'hh-006',
    userId: 'user-james-okonkwo',
    displayName: 'James Okonkwo',
    profileAddress: 'unit022@soralia.org',
    householdRole: 'FAMILY',
    residencyType: 'FAMILY',
    occupantSince: new Date('2024-01-20'),
  },
  {
    id: 'prof-fatima',
    householdId: 'hh-005',
    userId: 'user-fatima-hassan',
    displayName: 'Fatima Hassan',
    profileAddress: 'unit017@soralia.org',
    householdRole: 'FAMILY',
    residencyType: 'FAMILY',
    occupantSince: new Date('2023-09-01'),
  },
];

export const standardSeats: StandardSeatInput[] = [
  {
    id: 'seat-john',
    userId: 'user-john-smith',
    propertyId: 'prop-001',
    isPrimaryOwner: true,
    platformAddress: 'unit012@soralia.org',
  },
  {
    id: 'seat-sarah',
    userId: 'user-sarah-mitchell',
    propertyId: 'prop-002',
    isPrimaryOwner: true,
    platformAddress: 'unit008@soralia.org',
  },
  {
    id: 'seat-michael',
    userId: 'user-michael-chen',
    propertyId: 'prop-003',
    isPrimaryOwner: true,
    platformAddress: 'unit003@soralia.org',
  },
  {
    id: 'seat-robert',
    userId: 'user-robert-wilson',
    propertyId: 'prop-004',
    isPrimaryOwner: true,
    platformAddress: 'unit005@soralia.org',
  },
  {
    id: 'seat-anna',
    userId: 'user-anna-patel',
    propertyId: 'prop-004',
    isPrimaryOwner: false,
    platformAddress: 'unit005@soralia.org',
  },
  {
    id: 'seat-priya',
    userId: 'user-priya-naidoo',
    propertyId: 'prop-005',
    isPrimaryOwner: true,
    platformAddress: 'unit017@soralia.org',
  },
  {
    id: 'seat-marcus',
    userId: 'user-marcus-johnson',
    propertyId: 'prop-006',
    isPrimaryOwner: true,
    platformAddress: 'unit022@soralia.org',
  },
];

export const soloSeats: SoloSeatInput[] = [
  {
    id: 'seat-emma',
    userId: 'user-emma-williams',
    platformAddress: 'emma.williams@soralia.org',
    propertyId: 'prop-001',
    seatType: 'MEMBER',
    isComplimentary: true,
  },
  {
    id: 'seat-lisa',
    userId: 'user-lisa-chen',
    platformAddress: 'lisa.chen@soralia.org',
    propertyId: 'prop-003',
    seatType: 'MEMBER',
    isComplimentary: true,
  },
  {
    id: 'seat-james',
    userId: 'user-james-okonkwo',
    platformAddress: 'james.okonkwo@soralia.org',
    propertyId: 'prop-006',
    seatType: 'MEMBER',
    isComplimentary: true,
  },
  {
    id: 'seat-fatima',
    userId: 'user-fatima-hassan',
    platformAddress: 'fatima.hassan@soralia.org',
    propertyId: 'prop-005',
    seatType: 'MEMBER',
    isComplimentary: true,
  },
];

export const premiumSeats: PremiumSeatInput[] = [
  {
    id: 'prem-sarah',
    userId: 'user-sarah-mitchell',
    platformAddress: 'sarah.mitchell@soralia.org',
    portfolioName: 'Mitchell Properties',
    maxProperties: 3,
  },
  {
    id: 'prem-david',
    userId: 'user-david-vdm',
    platformAddress: 'david.van.der.merwe@soralia.org',
    portfolioName: 'VDM Holdings',
    maxProperties: 5,
  },
];
