import type { ServiceListingInput, ServiceReviewInput } from '../types';

export const serviceListings: ServiceListingInput[] = [
  {
    id: 'svc-gardening',
    providerId: 'user-mike-johnson',
    title: 'Garden Maintenance & Landscaping',
    description:
      'Professional garden maintenance including lawn mowing, trimming, weeding, and seasonal planting. 15 years experience in Cape Town gardens. References available.',
    category: 'GARDENING',
    priceType: 'HOURLY',
    price: '180',
    serviceAreas: ['Soralia Village', 'Muizenberg', 'St James'],
    availability: { weekdays: true, weekends: true, evenings: false },
    images: [
      'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400',
      'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=400',
    ],
    portfolio: [],
    contactMethods: ['phone', 'email'],
    verified: true,
    rating: 4.8,
    reviewCount: 12,
    status: 'ACTIVE',
    isPublished: true,
    termsAndConditions:
      'Payment due within 7 days. Materials extra. 24hr cancellation notice required.',
    cancellationPolicy:
      'Free cancellation up to 24 hours before service. 50% charge for same-day cancellation.',
  },
  {
    id: 'svc-plumbing',
    providerId: 'user-cape-plumbing',
    title: 'Emergency & Residential Plumbing',
    description:
      'Licensed plumbing services for all residential needs. 24/7 emergency callouts available. Fully insured with 5-year workmanship guarantee.',
    category: 'PLUMBING',
    priceType: 'HOURLY',
    price: '350',
    serviceAreas: ['Soralia Village', 'Muizenberg', 'Cape Town Southern Suburbs'],
    availability: { emergency: true, weekdays: true, weekends: true, evenings: true },
    licenseNumber: 'PL-2023-0456',
    insuranceExpiry: new Date('2027-12-31'),
    images: [
      'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=400',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    ],
    portfolio: [],
    contactMethods: ['phone', 'email'],
    verified: true,
    rating: 4.9,
    reviewCount: 28,
    status: 'ACTIVE',
    isPublished: true,
    termsAndConditions:
      'Quote provided before work begins. Materials charged at cost plus 15%. All work guaranteed.',
    cancellationPolicy:
      'Emergency calls: 2hr cancellation notice. Scheduled work: 24hr notice required.',
  },
  {
    id: 'svc-electrical',
    providerId: 'user-peter-nkosi',
    title: 'Residential Electrical Repairs',
    description:
      'Qualified electrician specializing in residential electrical work. COC certificates available. Safe, reliable service with competitive rates.',
    category: 'ELECTRICAL',
    priceType: 'HOURLY',
    price: '280',
    serviceAreas: ['Soralia Village', 'Muizenberg'],
    availability: { weekdays: true, weekends: false, evenings: false },
    licenseNumber: 'ELE-2022-0789',
    insuranceExpiry: new Date('2026-08-15'),
    images: [
      'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=400',
      'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400',
    ],
    portfolio: [],
    contactMethods: ['phone', 'email'],
    verified: true,
    rating: 4.7,
    reviewCount: 8,
    status: 'ACTIVE',
    isPublished: true,
    termsAndConditions:
      'All work complies with SANS 10142. COC certificates provided. 6-month workmanship guarantee.',
    cancellationPolicy:
      '24hr notice required for cancellation. Emergency work cannot be cancelled.',
  },
  {
    id: 'svc-cleaning',
    providerId: 'user-linda-fourie',
    title: 'Deep Cleaning & Housekeeping',
    description:
      'Thorough cleaning services for homes and apartments. Eco-friendly products used. Regular and one-time cleans available.',
    category: 'CLEANING',
    priceType: 'HOURLY',
    price: '120',
    serviceAreas: ['Soralia Village', 'Muizenberg', 'St James'],
    availability: { weekdays: true, weekends: true, evenings: false },
    images: [
      'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400',
      'https://images.unsplash.com/photo-1556912173-3bb406ef7e77?w=400',
    ],
    portfolio: [],
    contactMethods: ['phone', 'email'],
    verified: false,
    rating: 4.5,
    reviewCount: 15,
    status: 'ACTIVE',
    isPublished: true,
    termsAndConditions:
      'Eco-friendly products only. Keys handled securely. Satisfaction guarantee.',
    cancellationPolicy: '48hr notice required. Late cancellations may incur 50% charge.',
  },
  {
    id: 'svc-hoa-maintenance',
    providerId: 'user-hoa-services',
    title: 'HOA Community Maintenance Services',
    description:
      'Official HOA maintenance services including pool cleaning, common area upkeep, and emergency repairs. Services provided by certified HOA contractors.',
    category: 'MAINTENANCE',
    priceType: 'FREE',
    serviceAreas: ['Soralia Village'],
    availability: { weekdays: true, weekends: false, evenings: false },
    images: [
      'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=400',
      'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400',
    ],
    portfolio: [],
    contactMethods: ['phone', 'email'],
    verified: true,
    rating: 4.2,
    reviewCount: 45,
    status: 'ACTIVE',
    isPublished: true,
    termsAndConditions:
      'Services provided as part of HOA membership. Emergency services prioritized.',
    cancellationPolicy: 'Non-emergency services require 48hr notice.',
  },
  {
    id: 'svc-appliance-repair',
    providerId: 'user-mike-johnson',
    title: 'Appliance Repair Services',
    description:
      'Repair and maintenance of household appliances including washing machines, dishwashers, ovens, and refrigerators.',
    category: 'APPLIANCE_REPAIR',
    priceType: 'QUOTE',
    serviceAreas: ['Soralia Village', 'Muizenberg'],
    availability: { weekdays: true, weekends: true, evenings: false },
    images: ['https://images.unsplash.com/photo-1621905252478-2f1d6c0a6b2f?w=400'],
    portfolio: [],
    contactMethods: ['phone', 'email'],
    verified: false,
    rating: 0,
    reviewCount: 0,
    status: 'DRAFT',
    isPublished: false,
    termsAndConditions: 'Parts charged at cost plus 20%. 3-month workmanship guarantee.',
    cancellationPolicy: 'Callout fee applies for no-show appointments.',
  },
  {
    id: 'svc-pest-control',
    providerId: 'user-cape-plumbing',
    title: 'Pest Control & Prevention',
    description:
      'Professional pest control services using environmentally friendly methods. Ants, cockroaches, rodents, and other common pests.',
    category: 'PEST_CONTROL',
    priceType: 'FIXED',
    price: '850',
    serviceAreas: ['Soralia Village', 'Muizenberg', 'St James'],
    availability: { weekdays: true, weekends: false, evenings: false },
    licenseNumber: 'PEST-2024-0123',
    insuranceExpiry: new Date('2026-06-30'),
    images: ['https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400'],
    portfolio: [],
    contactMethods: ['phone', 'email'],
    verified: true,
    rating: 4.6,
    reviewCount: 9,
    status: 'ACTIVE',
    isPublished: true,
    termsAndConditions:
      'Eco-friendly treatments only. 90-day guarantee. Follow-up inspections included.',
    cancellationPolicy: '24hr notice required. Late cancellations charged at 50%.',
  },
  {
    id: 'svc-security',
    providerId: 'user-hoa-services',
    title: 'Security System Installation & Maintenance',
    description:
      'HOA-approved security services including alarm systems, CCTV installation, and access control systems. Competitive rates for community members.',
    category: 'SECURITY',
    priceType: 'QUOTE',
    serviceAreas: ['Soralia Village'],
    availability: { weekdays: true, weekends: false, evenings: false },
    images: [
      'https://images.unsplash.com/photo-1558002038-1055907df827?w=400',
      'https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=400',
    ],
    portfolio: [],
    contactMethods: ['phone', 'email'],
    verified: true,
    rating: 4.4,
    reviewCount: 7,
    status: 'ACTIVE',
    isPublished: true,
    termsAndConditions:
      'HOA-approved equipment only. Professional installation guaranteed. 2-year warranty.',
    cancellationPolicy: 'Standard cancellation terms apply. Deposit may be non-refundable.',
  },
];

export const serviceReviews: ServiceReviewInput[] = [
  {
    id: 'review-gardening-1',
    listingId: 'svc-gardening',
    reviewerId: 'user-john-smith',
    rating: 5,
    title: 'Excellent service!',
    comment:
      'Mike did a fantastic job on our garden. Very professional and the results are amazing. Highly recommended!',
    serviceDate: new Date('2026-03-15'),
    responseQuality: 5,
    isPublished: true,
  },
  {
    id: 'review-plumbing-1',
    listingId: 'svc-plumbing',
    reviewerId: 'user-sarah-mitchell',
    rating: 5,
    title: 'Emergency plumbing heroes!',
    comment:
      'Called them at 2am for a burst pipe. They arrived within an hour and fixed everything perfectly. Lifesavers!',
    serviceDate: new Date('2026-03-20'),
    responseQuality: 5,
    isPublished: true,
  },
  {
    id: 'review-electrical-1',
    listingId: 'svc-electrical',
    reviewerId: 'user-michael-chen',
    rating: 4,
    title: 'Good work, fair price',
    comment:
      'Peter replaced our faulty outlets. Work was done well and he explained everything clearly. Would use again.',
    serviceDate: new Date('2026-03-10'),
    responseQuality: 4,
    isPublished: true,
  },
  {
    id: 'review-cleaning-1',
    listingId: 'svc-cleaning',
    reviewerId: 'user-emma-williams',
    rating: 5,
    title: 'Spotless!',
    comment:
      'Linda did an amazing deep clean of our home. Very thorough and used eco-friendly products as promised.',
    serviceDate: new Date('2026-03-25'),
    responseQuality: 5,
    isPublished: true,
  },
];
