import type { UserInput } from '../types';

export const users: UserInput[] = [
  {
    id: 'user-john-smith',
    email: 'john.smith@example.com',
    name: 'John Smith',
    role: 'RESIDENT',
    phone: '+27 82 123 4567',
    interests: ['gardening', 'tennis'],
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    books: [
      {
        id: 'book-1',
        title: "The Gardener's Guide to South African Plants",
        author: 'Patricia Anne',
        coverUrl: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400',
      },
      {
        id: 'book-2',
        title: 'Fynbos: A Field Guide',
        author: 'Gideon Smith',
        coverUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400',
      },
      {
        id: 'book-3',
        title: 'Water-Wise Gardening in South Africa',
        author: 'Noelle Johnson',
        coverUrl: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400',
      },
    ],
  },
  {
    id: 'user-sarah-mitchell',
    email: 'sarah.mitchell@example.com',
    name: 'Sarah Mitchell',
    role: 'BOARD',
    phone: '+27 82 234 5678',
    interests: ['gardening', 'book-club'],
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    books: [
      {
        id: 'book-4',
        title: 'The Promise',
        author: 'Damon Galgut',
        coverUrl: 'https://images.unsplash.com/photo-1541963463532-d68292c34b19?w=400',
      },
      {
        id: 'book-5',
        title: 'Born a Crime',
        author: 'Trevor Noah',
        coverUrl: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400',
      },
      {
        id: 'book-6',
        title: 'Community Governance Handbook',
        author: 'HOA Press',
        coverUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400',
      },
      {
        id: 'book-7',
        title: 'The Four Winds',
        author: 'Kristin Hannah',
        coverUrl: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400',
      },
    ],
  },
  {
    id: 'user-michael-chen',
    email: 'michael.chen@example.com',
    name: 'Michael Chen',
    role: 'RESIDENT',
    phone: '+27 82 345 6789',
    interests: ['fitness', 'photography'],
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
    books: [
      {
        id: 'book-8',
        title: 'Understanding Exposure',
        author: 'Bryan Peterson',
        coverUrl: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400',
      },
      {
        id: 'book-9',
        title: "The Photographer's Eye",
        author: 'Michael Freeman',
        coverUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400',
      },
    ],
  },
  {
    id: 'user-emma-williams',
    email: 'emma.williams@example.com',
    name: 'Emma Williams',
    role: 'RESIDENT',
    phone: '+27 82 456 7890',
    interests: ['book-club', 'cooking'],
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
    books: [
      {
        id: 'book-10',
        title: 'The Joy of Cooking',
        author: 'Irma Rombauer',
        coverUrl: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400',
      },
      {
        id: 'book-11',
        title: 'Circe',
        author: 'Madeline Miller',
        coverUrl: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400',
      },
      {
        id: 'book-12',
        title: 'Where the Crawdads Sing',
        author: 'Delia Owens',
        coverUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400',
      },
      {
        id: 'book-13',
        title: 'Cape Malay Cooking',
        author: 'Fatima Sydow',
        coverUrl: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400',
      },
      {
        id: 'book-14',
        title: 'The Midnight Library',
        author: 'Matt Haig',
        coverUrl: 'https://images.unsplash.com/photo-1541963463532-d68292c34b19?w=400',
      },
    ],
  },
  {
    id: 'user-david-vdm',
    email: 'david.van.der.merwe@example.com',
    name: 'David van der Merwe',
    role: 'ADMIN',
    phone: '+27 82 567 8901',
    interests: ['volunteering', 'conservation'],
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
    books: [
      {
        id: 'book-15',
        title: 'Silent Spring',
        author: 'Rachel Carson',
        coverUrl: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400',
      },
      {
        id: 'book-16',
        title: 'The Hidden Life of Trees',
        author: 'Peter Wohlleben',
        coverUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400',
      },
      {
        id: 'book-17',
        title: 'Fynbos of the Cape Peninsula',
        author: 'Richard Cowling',
        coverUrl: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400',
      },
    ],
  },
  {
    id: 'user-lisa-chen',
    email: 'lisa.chen@example.com',
    name: 'Lisa Chen',
    role: 'RESIDENT',
    phone: '+27 82 678 9012',
    interests: ['yoga', 'photography'],
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa',
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa',
    books: [
      {
        id: 'book-18',
        title: 'Light on Yoga',
        author: 'B.K.S. Iyengar',
        coverUrl: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400',
      },
      {
        id: 'book-19',
        title: 'The Yoga Bible',
        author: 'Christina Brown',
        coverUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400',
      },
    ],
  },
  {
    id: 'user-robert-wilson',
    email: 'robert.wilson@example.com',
    name: 'Robert Wilson',
    role: 'COMMITTEE',
    phone: '+27 82 789 0123',
    interests: ['governance', 'finance', 'community'],
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Robert',
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Robert',
    books: [
      {
        id: 'book-20',
        title: 'Sectional Titles Schemes Management Act',
        author: 'LexisNexis',
        coverUrl: 'https://images.unsplash.com/photo-1541963463532-d68292c34b19?w=400',
      },
      {
        id: 'book-21',
        title: 'Financial Management for HOAs',
        author: 'Community Living Press',
        coverUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400',
      },
    ],
  },
  {
    id: 'user-anna-patel',
    email: 'anna.patel@example.com',
    name: 'Anna Patel',
    role: 'RESIDENT',
    phone: '+27 82 890 1234',
    interests: ['cooking', 'gardening', 'book-club'],
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Anna',
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Anna',
    books: [
      {
        id: 'book-22',
        title: 'Indian Vegetarian Cooking',
        author: 'Madhur Jaffrey',
        coverUrl: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400',
      },
      {
        id: 'book-23',
        title: 'The Alchemist',
        author: 'Paulo Coelho',
        coverUrl: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400',
      },
    ],
  },
  {
    id: 'user-marcus-johnson',
    email: 'marcus.johnson@example.com',
    name: 'Marcus Johnson',
    role: 'RESIDENT',
    phone: '+27 82 901 2345',
    interests: ['fitness', 'music', 'volunteering'],
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus',
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus',
    books: [
      {
        id: 'book-24',
        title: 'Becoming',
        author: 'Michelle Obama',
        coverUrl: 'https://images.unsplash.com/photo-1541963463532-d68292c34b19?w=400',
      },
      {
        id: 'book-25',
        title: 'The Art of Resilience',
        author: 'Ross Edgley',
        coverUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400',
      },
    ],
  },
  {
    id: 'user-priya-naidoo',
    email: 'priya.naidoo@example.com',
    name: 'Priya Naidoo',
    role: 'RESIDENT',
    phone: '+27 82 012 3456',
    interests: ['yoga', 'cooking'],
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya',
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya',
    books: [
      {
        id: 'book-26',
        title: 'Yoga Anatomy',
        author: 'Leslie Kaminoff',
        coverUrl: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400',
      },
      {
        id: 'book-27',
        title: 'The Flavor Equation',
        author: 'Nik Sharma',
        coverUrl: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400',
      },
      {
        id: 'book-28',
        title: 'Eat, Pray, Love',
        author: 'Elizabeth Gilbert',
        coverUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400',
      },
    ],
  },
  {
    id: 'user-james-okonkwo',
    email: 'james.okonkwo@example.com',
    name: 'James Okonkwo',
    role: 'RESIDENT',
    phone: '+27 82 111 2222',
    interests: ['football', 'community'],
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
    books: [
      {
        id: 'book-29',
        title: 'Shoe Dog',
        author: 'Phil Knight',
        coverUrl: 'https://images.unsplash.com/photo-1541963463532-d68292c34b19?w=400',
      },
    ],
  },
  {
    id: 'user-fatima-hassan',
    email: 'fatima.hassan@example.com',
    name: 'Fatima Hassan',
    role: 'RESIDENT',
    phone: '+27 82 333 4444',
    interests: ['art', 'gardening'],
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fatima',
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fatima',
    books: [
      {
        id: 'book-30',
        title: 'The Color of Water',
        author: 'James McBride',
        coverUrl: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400',
      },
      {
        id: 'book-31',
        title: 'Botany for Gardeners',
        author: 'Brian Capon',
        coverUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400',
      },
      {
        id: 'book-32',
        title: 'The Secret Garden',
        author: 'Frances Hodgson Burnett',
        coverUrl: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400',
      },
    ],
  },
  {
    id: 'user-mike-johnson',
    email: 'mike.johnson.gardener@example.com',
    name: 'Mike Johnson',
    role: 'RESIDENT',
    phone: '+27 82 345 6789',
    interests: ['gardening', 'landscaping'],
  },
  {
    id: 'user-susan-vdm',
    email: 'susan.van.der.merwe@example.com',
    name: 'Susan van der Merwe',
    role: 'RESIDENT',
    phone: '+27 82 456 7890',
    interests: ['home-improvement', 'diy'],
  },
  {
    id: 'user-peter-nkosi',
    email: 'peter.nkosi@example.com',
    name: 'Peter Nkosi',
    role: 'RESIDENT',
    phone: '+27 82 567 8901',
    interests: ['electronics', 'home-improvement'],
  },
  {
    id: 'user-linda-fourie',
    email: 'linda.fourie@example.com',
    name: 'Linda Fourie',
    role: 'RESIDENT',
    phone: '+27 82 678 9012',
    interests: ['cleaning', 'organization'],
  },
  {
    id: 'user-hoa-services',
    email: 'hoa.services@example.com',
    name: 'Soralia HOA Services',
    role: 'ADMIN',
    phone: '+27 21 123 4567',
    interests: ['community', 'maintenance'],
  },
  {
    id: 'user-cape-plumbing',
    email: 'cape.plumbing@example.com',
    name: 'Cape Plumbing Solutions',
    role: 'AGENT',
    phone: '+27 21 987 6543',
    interests: ['plumbing', 'emergency-services'],
  },
];
