import type { ResourceInput } from '../types';

export const resources: ResourceInput[] = [
  {
    id: 'res-arch-review-form',
    title: 'Architectural Review Application Form',
    description:
      'Complete this form before making any exterior modifications to your property. Includes guidelines for paint colours, fencing, landscaping, and structural changes. All applications require board approval.',
    category: 'ARCHITECTURAL',
    fileUrl: '/resources/docs/architectural-review-form.pdf',
    fileType: 'application/pdf',
    fileSize: 245000,
    version: '3.2',
    visibility: 'ALL_RESIDENTS',
    authorId: 'user-sarah-mitchell',
    publishedAt: new Date('2026-01-15'),
  },
  {
    id: 'res-arch-guidelines',
    title: 'Architectural Design Guidelines',
    description:
      'Comprehensive guidelines for all exterior modifications including approved colour palettes, fencing specifications, roofing materials, and landscaping requirements for Soralia Village.',
    category: 'ARCHITECTURAL',
    fileUrl: '/resources/docs/design-guidelines.pdf',
    fileType: 'application/pdf',
    fileSize: 1820000,
    version: '2.0',
    visibility: 'ALL_RESIDENTS',
    authorId: 'user-sarah-mitchell',
    publishedAt: new Date('2025-11-01'),
  },
  {
    id: 'res-eng-site-plan',
    title: 'Master Site Plan',
    description:
      'Engineering site plan showing all phases of Soralia Village development, including road layouts, utility corridors, common areas, and future expansion zones.',
    category: 'ENGINEERING',
    fileUrl: '/resources/docs/master-site-plan.pdf',
    fileType: 'application/pdf',
    fileSize: 4500000,
    version: '1.5',
    visibility: 'ALL_RESIDENTS',
    authorId: 'user-david-vdm',
    publishedAt: new Date('2025-06-20'),
  },
  {
    id: 'res-eng-drainage',
    title: 'Stormwater Drainage Plan',
    description:
      'Detailed drainage engineering plans for the estate. Important for understanding water flow and flood risk areas. Updated after 2025 wet season improvements.',
    category: 'ENGINEERING',
    fileUrl: '/resources/docs/drainage-plan.pdf',
    fileType: 'application/pdf',
    fileSize: 3200000,
    version: '2.1',
    visibility: 'ALL_RESIDENTS',
    authorId: 'user-david-vdm',
    publishedAt: new Date('2025-09-10'),
  },
  {
    id: 'res-gov-hoa-rules',
    title: 'HOA Conduct Rules & Bylaws',
    description:
      'The official rules and regulations governing Soralia Village. Covers noise restrictions, pet policies, parking regulations, rental restrictions, and dispute resolution procedures. All residents must comply.',
    category: 'GOVERNANCE',
    fileUrl: '/resources/docs/hoa-rules-bylaws.pdf',
    fileType: 'application/pdf',
    fileSize: 890000,
    version: '4.0',
    visibility: 'ALL_RESIDENTS',
    authorId: 'user-sarah-mitchell',
    publishedAt: new Date('2026-02-01'),
  },
  {
    id: 'res-gov-constitution',
    title: 'HOA Constitution',
    description:
      'The constitution of the Soralia Village Homeowners Association. Defines the legal structure, membership obligations, board elections, and amendment procedures.',
    category: 'GOVERNANCE',
    fileUrl: '/resources/docs/hoa-constitution.pdf',
    fileType: 'application/pdf',
    fileSize: 520000,
    version: '2.3',
    visibility: 'ALL_RESIDENTS',
    authorId: 'user-sarah-mitchell',
    publishedAt: new Date('2025-03-15'),
  },
  {
    id: 'res-gov-meeting-minutes-template',
    title: 'AGM Meeting Minutes Template',
    description:
      'Standard template for recording annual general meeting minutes. Use this format for all community meetings to ensure consistent record keeping.',
    category: 'GOVERNANCE',
    fileUrl: '/resources/docs/agm-minutes-template.docx',
    fileType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    fileSize: 45000,
    version: '1.0',
    visibility: 'COMMITTEE_ONLY',
    authorId: 'user-robert-wilson',
    publishedAt: new Date('2025-08-01'),
  },
  {
    id: 'res-fin-annual-budget',
    title: 'Annual Budget 2026',
    description:
      'Detailed budget breakdown for the 2026 financial year including maintenance reserves, insurance, utilities, and capital improvement allocations.',
    category: 'FINANCIAL',
    fileUrl: '/resources/docs/annual-budget-2026.pdf',
    fileType: 'application/pdf',
    fileSize: 680000,
    version: '1.0',
    visibility: 'OWNERS_ONLY',
    authorId: 'user-robert-wilson',
    publishedAt: new Date('2026-01-10'),
  },
  {
    id: 'res-fin-levy-schedule',
    title: 'Monthly Levy Schedule',
    description:
      'Current levy amounts per unit type, payment due dates, and penalty structure for late payments. Includes breakdown of what levies cover.',
    category: 'FINANCIAL',
    fileUrl: '/resources/docs/levy-schedule.pdf',
    fileType: 'application/pdf',
    fileSize: 180000,
    version: '2026.1',
    visibility: 'OWNERS_ONLY',
    authorId: 'user-robert-wilson',
    publishedAt: new Date('2026-01-01'),
  },
  {
    id: 'res-legal-title-deed-guide',
    title: 'Title Deed Conditions',
    description:
      'Consolidated title deed conditions applicable to all properties in Soralia Village. Includes servitudes, building line restrictions, and usage limitations.',
    category: 'LEGAL',
    fileUrl: '/resources/docs/title-deed-conditions.pdf',
    fileType: 'application/pdf',
    fileSize: 1200000,
    version: '1.0',
    visibility: 'OWNERS_ONLY',
    authorId: 'user-david-vdm',
    publishedAt: new Date('2025-04-20'),
  },
  {
    id: 'res-legal-rental-agreement',
    title: 'Standard Rental Agreement Template',
    description:
      'HOA-approved rental agreement template that must be used for all lease arrangements. Includes clauses requiring tenant registration with the HOA.',
    category: 'LEGAL',
    fileUrl: '/resources/docs/rental-agreement-template.docx',
    fileType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    fileSize: 95000,
    version: '3.0',
    visibility: 'OWNERS_ONLY',
    authorId: 'user-david-vdm',
    publishedAt: new Date('2025-07-15'),
  },
  {
    id: 'res-diy-garden-guide',
    title: 'Water-Wise Gardening Guide',
    description:
      'Practical guide to maintaining a beautiful garden while conserving water. Includes indigenous plant recommendations, irrigation tips, and seasonal planting calendars for the Cape region.',
    category: 'DIY',
    fileUrl: '/resources/docs/water-wise-gardening.pdf',
    fileType: 'application/pdf',
    fileSize: 2100000,
    version: '1.0',
    visibility: 'ALL_RESIDENTS',
    authorId: 'user-john-smith',
    publishedAt: new Date('2025-10-01'),
  },
  {
    id: 'res-diy-home-maintenance',
    title: 'Home Maintenance Checklist',
    description:
      'Seasonal home maintenance checklist to keep your property in top condition. Covers gutters, plumbing, electrical, painting, and garden upkeep tasks.',
    category: 'DIY',
    fileUrl: '/resources/docs/home-maintenance-checklist.pdf',
    fileType: 'application/pdf',
    fileSize: 340000,
    version: '1.0',
    visibility: 'ALL_RESIDENTS',
    authorId: 'user-john-smith',
    publishedAt: new Date('2025-12-01'),
  },
  {
    id: 'res-board-q4-2025',
    title: 'Board Report Q4 2025',
    description:
      'Quarterly board report covering maintenance updates, financial summary, community initiatives, and upcoming projects for Q4 2025.',
    category: 'BOARD_REPORT',
    fileUrl: '/resources/docs/board-report-q4-2025.pdf',
    fileType: 'application/pdf',
    fileSize: 750000,
    version: '1.0',
    visibility: 'ALL_RESIDENTS',
    authorId: 'user-sarah-mitchell',
    publishedAt: new Date('2025-12-20'),
  },
];
