/**
 * build-overage-invoice-pdf.ts — AI Pool Overage Surcharge Invoice PDF Generator
 * Phase 109-01 — Task 1
 *
 * Pure function: OverageInvoiceData → Uint8Array PDF bytes.
 * Uses shared PDF utilities from @shared/api/pdf-utils.
 * Layout: Header → Account → Usage Summary → Charge Breakdown → Footer.
 */
import { PDFDocument, rgb } from 'pdf-lib';
import {
  A4_WIDTH,
  A4_HEIGHT,
  MARGIN,
  BODY_SIZE,
  HEADER_SIZE,
  TITLE_SIZE,
  LINE_HEIGHT,
  createPdfContext,
  drawSectionHeader,
  drawLine,
  drawWrappedText,
  checkPageBreak,
  PdfContext,
} from '@/shared/api/pdf-utils';

// ── Data interface ──
export interface OverageInvoiceData {
  tenantName: string;
  tenantLegalName?: string | null;
  billingMonth: string;
  quota: number;
  tokensUsed: number;
  overageTokens: number;
  overageCostZAR: string;
  costPerThousandTokens: number;
  invoiceNumber: string;
  invoiceDate: string;
}

// ── Helpers ──
function fmtNum(n: number): string {
  return n.toLocaleString('en-ZA');
}

function fmtZAR(amount: string | number): string {
  const value = typeof amount === 'string' ? parseFloat(amount) : amount;
  return `R${value.toFixed(2)}`;
}

// ── Section rendering ──
function renderAccountSection(
  pdfDoc: PDFDocument,
  ctx: PdfContext,
  data: OverageInvoiceData
): void {
  drawSectionHeader(ctx, 'ACCOUNT DETAILS');
  drawLine(ctx, `Tenant: ${data.tenantName}`);
  if (data.tenantLegalName) {
    drawLine(ctx, `Legal Name: ${data.tenantLegalName}`);
  }
  drawLine(ctx, `Billing Period: ${data.billingMonth}`);
  ctx.y -= LINE_HEIGHT * 0.5;
}

function renderUsageSection(pdfDoc: PDFDocument, ctx: PdfContext, data: OverageInvoiceData): void {
  drawSectionHeader(ctx, 'USAGE SUMMARY');
  drawLine(ctx, `Monthly AI Token Quota: ${fmtNum(data.quota)}`);
  drawLine(ctx, `Tokens Consumed: ${fmtNum(data.tokensUsed)}`);
  drawLine(ctx, `Overage Tokens: ${fmtNum(data.overageTokens)}`);
  ctx.y -= LINE_HEIGHT * 0.5;
}

function renderChargeSection(pdfDoc: PDFDocument, ctx: PdfContext, data: OverageInvoiceData): void {
  drawSectionHeader(ctx, 'CHARGE BREAKDOWN');

  const rateStr = `R${data.costPerThousandTokens.toFixed(2)}`;
  drawLine(ctx, `Rate per 1,000 tokens: ${rateStr}`);

  const overageCostNum = parseFloat(data.overageCostZAR) || 0;
  const subtotal = overageCostNum;
  const vatRate = 0.15;
  const vatAmount = subtotal * vatRate;
  const grandTotal = subtotal + vatAmount;

  drawLine(ctx, `Overage Cost (${fmtNum(data.overageTokens)} tokens): ${fmtZAR(subtotal)}`);
  ctx.y -= LINE_HEIGHT * 0.2;
  drawLine(ctx, `Subtotal: ${fmtZAR(subtotal)}`);
  drawLine(ctx, `VAT (15%): ${fmtZAR(vatAmount)}`);
  ctx.y -= LINE_HEIGHT * 0.2;
  drawLine(ctx, `Grand Total: ${fmtZAR(grandTotal)}`, { font: ctx.bold });
  ctx.y -= LINE_HEIGHT * 0.5;
}

function renderFooter(pdfDoc: PDFDocument, ctx: PdfContext): void {
  checkPageBreak(pdfDoc, ctx, LINE_HEIGHT * 5);
  ctx.y -= LINE_HEIGHT;
  ctx.page.drawLine({
    start: { x: MARGIN, y: ctx.y },
    end: { x: A4_WIDTH - MARGIN, y: ctx.y },
    thickness: 0.5,
    color: rgb(0.4, 0.4, 0.4),
  });
  ctx.y -= LINE_HEIGHT * 1.5;
  drawWrappedText(
    pdfDoc,
    ctx,
    'This invoice was automatically generated by the NetComplex AI Pool billing system. For disputes, contact your platform administrator.'
  );
}

// ── PDF Builder ──
export async function buildOverageInvoicePdf(data: OverageInvoiceData): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();

  pdfDoc.setTitle(`AI Overage Invoice — ${data.invoiceNumber}`);
  pdfDoc.setAuthor('NetComplex Platform');
  pdfDoc.setCreationDate(new Date());
  pdfDoc.setProducer('NetComplex AI Pool Billing');

  const ctx = await createPdfContext(pdfDoc);

  // ── Header Block ──
  ctx.page.drawText('AI POOL OVERAGE SURCHARGE', {
    x: MARGIN,
    y: ctx.y,
    size: TITLE_SIZE,
    font: ctx.bold,
    color: rgb(0, 0, 0),
  });
  ctx.y -= LINE_HEIGHT * 2;

  drawLine(ctx, `INVOICE`);
  drawLine(ctx, `Invoice Number: ${data.invoiceNumber}`);
  drawLine(ctx, `Invoice Date: ${data.invoiceDate}`);
  drawLine(ctx, `Tenant: ${data.tenantName}`);
  ctx.y -= LINE_HEIGHT * 0.5;

  // ── Section 1: Account ──
  renderAccountSection(pdfDoc, ctx, data);

  // ── Section 2: Usage Summary ──
  renderUsageSection(pdfDoc, ctx, data);

  // ── Section 3: Charge Breakdown ──
  renderChargeSection(pdfDoc, ctx, data);

  // ── Footer ──
  renderFooter(pdfDoc, ctx);

  return pdfDoc.save();
}
